version: 2.1
orbs:
  cypress: cypress-io/cypress@1
jobs:
  build:
    docker:
      - image: circleci/node:12.0-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - run:
          name: Prepare
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Unit Test (with coverage)
          command: npm run coverage
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - run:
          name: Prepare demo
          command: ./scripts/demo.sh
      - persist_to_workspace:
          root: .
          paths:
            - ./demo
            - ./storybook-static
  update-demos:
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "e3:56:4b:3d:1c:58:a6:f9:7d:24:0a:90:01:77:aa:fb"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Prepare
          command: |
            npm install -g --silent gh-pages
            git config user.email "ci-build@wikimedia.org"
            git config user.name "ci-build"
      - run:
          name: Deploy demo
          command: |
            gh-pages --dist . -m "Update demo [ci skip]"
workflows:
  version: 2
  build:
    jobs:
      - build
      - update-demos:
          requires:
            - build
          filters:
            branches:
              only: main
      - cypress/install
      - cypress/run:
          name: Chrome
          requires:
            - cypress/install
          executor: cypress/browsers-chrome73-ff68
          group: chrome
          browser: chrome

      
